### PR TITLE
Stop kludging file extension into classifier

### LINKED ISSUE #22: wrong filename used for artifacts of type "test-jar"
## Steps to Reproduce
1. Publish test JARs for a signed artifact. For example, write some basic test sources and include this in a POM:
```XML
  <project>
    <!-- ... omitted other sections ... -->
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>test-jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <configuration>
                    <passphrase>${gpg.passphrase}</passphrase>
                    <useAgent>true</useAgent>
                </configuration>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <!-- ... omitted other sections ... -->
</project>
```
2. In another artifact, reference the test JAR artifact and add PGP Verify such that it fails on a bad sig. For example:
```XML
  <project>
    <!-- ... omitted other sections ... -->
    <dependencies>
         <dependency>
             <groupId>com.github.some-repo</groupId>
             <artifactId>my-artifact</artifactId>
             <type>test-jar</type>
             <scope>test</scope>
         </dependency>
    <dependencies>
    <!-- ... omitted other sections ... -->
    <build>
        <!-- ... omitted other sections ... -->
        <plugins>
            <plugin>
                <groupId>com.github.s4u.plugins</groupId>
                <artifactId>pgpverify-maven-plugin</artifactId>
                <configuration>
                    <failNoSignature>true</failNoSignature>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <phase>verify</phase>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <!-- ... omitted other sections ... -->
  </project>
```
3. Attempt to build using `mvn clean install`.

## Expected Results
The signature file for the test JAR is requested as `my-artifact-1.0.0-tests.jar.asc`, and the build passes without issue.

## Actual Results
The signature file for the test JAR is requested as `my-artifact-1.0.0-tests.test-jar.asc`, and the build fails.

### PR DESCRIPTION
**Pull request by Kortanul**
Previous approach blindly appended ".asc" to the classifier, breaking resolution for special artifacts like test JARs. Maven resolves these artifacts to a packaging type and file extension of "jar", but wasn't doing this here because the classifiers didn't match (since it had ".asc" at the end).

New approach provides the original classifier to Maven for it to apply standard look-up rules, then uses a new AscArtifactHandler that decorates the ArtifactHandler Maven returns for the artifact so that we fetch an artifact ending in ".asc".

Closes #22.

### CODE REVIEW

**Comment by Kortanul** [comment]
FYI looks like more work might be needed here. now I'm running into issues with POM ASC resolution on test-jar artifacts. for an artifact like `my-artifact-1.0.0-tests.jar`, the POM would be `my-artifact/pom.xml` with an ASC file of `my-artifact-1.0.0.pom.asc` but it's looking for `my-artifact-1.0.0-tests.pom.asc`,

File: src/main/java/com/github/s4u/plugins/AscArtifactHandler.java [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+    }
+
+    @Override
+    public String getPackaging() {
+        return wrappedHandler.getPackaging();
+    }
+
+    @Override
+    public boolean isIncludesDependencies() {
+        return false;
```
Comment (slawekjaranowski) [inline src/main/java/com/github/s4u/plugins/AscArtifactHandler.java]: Why you don't use wrappedHandler?

Comment (Kortanul) [reply src/main/java/com/github/s4u/plugins/AscArtifactHandler.java]: good catch -- it was supposed to be delegated. this is an error.

**Comment by Kortanul** [comment]
i have more to commit shortly to fix the pom resolution issue I was mentioning.

**Comment by slawekjaranowski** [comment]
OK. OK, I will wait for new commits.

**Comment by Kortanul** [comment]
@slawekjaranowski this is ready for review once again.

**Comment by Kortanul** [comment]
btw I ran into a vulnerability in e215ff3 that was introduced in https://github.com/s4u/pgpverify-maven-plugin/pull/19. if PGP Verify fails to resolve the POM (due to an unknown defect, or some issue, etc in PGP Verify), but Maven ends up resolving the POM successfully, the POM will pass by without validation.

there's not really any easy answer (except perhaps an option / setting to require POMs to download?) to this issue since some artifacts are published without a POM. just wanted to point out that it could be a gotcha.

**Comment by slawekjaranowski** [comment]
Thanks for your collaborations.
In next a few days I will prepare next release.
